-- ************************** SqlDBM: PostgreSQL **************************
-- * Generated by SqlDBM: Pipeline Gov by henriquerodrigues8901@gmail.com *


-- ************************************** municipios
CREATE TABLE IF NOT EXISTS municipios
(
 municipioId   serial NOT NULL,
 nomeMunicipio varchar(100) NOT NULL,
 cdgMunicipio  varchar(7) NOT NULL,
 CONSTRAINT PK_4_1 PRIMARY KEY ( municipioId )
);



-- ************************** SqlDBM: PostgreSQL **************************
-- * Generated by SqlDBM: Pipeline Gov by henriquerodrigues8901@gmail.com *


-- ************************************** escolas_enem
CREATE TABLE IF NOT EXISTS escolas_enem
(
 escolaId       serial NOT NULL,
 municipioId    serial NOT NULL,
 dependenciaAdm varchar(10) NOT NULL,
 localizacao    varchar(10) NOT NULL,
 sitFunc        varchar(1) NOT NULL,
 CONSTRAINT PK_3 PRIMARY KEY ( escolaId ),
 CONSTRAINT FK_1 FOREIGN KEY ( municipioId ) REFERENCES municipios ( municipioId ),
 CONSTRAINT dependenciaCheck CHECK ( dependenciaAdm in ('federal', 'estadual', 'municipal', 'privada') ),
 CONSTRAINT localizacaoCheck CHECK ( localizacao in ('urbana', 'rural') )
);



-- ************************** SqlDBM: PostgreSQL **************************
-- * Generated by SqlDBM: Pipeline Gov by henriquerodrigues8901@gmail.com *


-- ************************************** inscricoes_enem
CREATE TABLE IF NOT EXISTS inscricoes_enem
(
 inscricaoId   serial NOT NULL,
 escolaId      serial NOT NULL,
 nuInscricao   varchar(12) NOT NULL,
 faixaEtaria   varchar(2) NOT NULL,
 sexo          varchar(1) NOT NULL,
 estadoCivil   varchar(1) NOT NULL,
 corRaca       varchar(1) NOT NULL,
 nacionalidade varchar(1) NOT NULL,
 stConclusao   varchar(1) NOT NULL,
 anoConcluiu   varchar(2) NOT NULL,
 tipoEscola    varchar(1) NOT NULL,
 tipoEnsino    varchar(1) NOT NULL,
 treineiro     varchar(1) NOT NULL,
 CONSTRAINT PK_2 PRIMARY KEY ( inscricaoId ),
 CONSTRAINT FK_1 FOREIGN KEY ( escolaId ) REFERENCES escolas_enem ( escolaId ),
 CONSTRAINT sexoCheck CHECK ( sexo in ('m', 'f') )
);



-- ************************** SqlDBM: PostgreSQL **************************
-- * Generated by SqlDBM: Pipeline Gov by henriquerodrigues8901@gmail.com *


-- ************************************** provas_enem
CREATE TABLE IF NOT EXISTS provas_enem
(
 provaId       serial NOT NULL,
 inscricaoId   serial NOT NULL,
 presencaCn    varchar(1) NOT NULL,
 notaCn        float4 NOT NULL,
 presencaCh    varchar(1) NOT NULL,
 notaCh        float4 NOT NULL,
 presencaLc    varchar(1) NOT NULL,
 notaLc        float4 NOT NULL,
 presencaMt    varchar(1) NOT NULL,
 notaMt        float4 NOT NULL,
 lingua        varchar(8) NOT NULL,
 statusRedacao varchar(1) NOT NULL,
 notaComp1     float4 NOT NULL,
 notaComp2     float4 NOT NULL,
 notaComp3     float4 NOT NULL,
 notaComp4     float4 NOT NULL,
 notaComp5     float4 NOT NULL,
 notaRedacao   float4 NOT NULL,
 CONSTRAINT PK_4 PRIMARY KEY ( provaId ),
 CONSTRAINT FK_1 FOREIGN KEY ( inscricaoId ) REFERENCES inscricoes_enem ( inscricaoId ),
 CONSTRAINT linguaCheck CHECK ( lingua in ('ingles', 'espanhol') )
);



-- STANGING
CREATE TABLE stg_microdados_enem (
    id SERIAL primary key,
	NU_INSCRICAO VARCHAR(255),
    NU_ANO VARCHAR(4),
    TP_FAIXA_ETARIA VARCHAR(2),
    TP_SEXO VARCHAR(1),
    TP_ESTADO_CIVIL VARCHAR(1),
    TP_COR_RACA VARCHAR(1),
    TP_NACIONALIDADE VARCHAR(1),
    TP_ST_CONCLUSAO VARCHAR(1),
    TP_ANO_CONCLUIU VARCHAR(1),
    TP_ESCOLA VARCHAR(1),
    TP_ENSINO VARCHAR(1),
    IN_TREINEIRO VARCHAR(1),
    CO_MUNICIPIO_ESC VARCHAR(7),
    NO_MUNICIPIO_ESC VARCHAR(150),
    CO_UF_ESC VARCHAR(2),
    SG_UF_ESC VARCHAR(2),
    TP_DEPENDENCIA_ADM_ESC VARCHAR(1),
    TP_LOCALIZACAO_ESC VARCHAR(1),
    TP_SIT_FUNC_ESC VARCHAR(1),
    CO_MUNICIPIO_PROVA VARCHAR(7),
    NO_MUNICIPIO_PROVA VARCHAR(150),
    CO_UF_PROVA VARCHAR(2),
    SG_UF_PROVA VARCHAR(2),
    TP_PRESENCA_CN VARCHAR(1),
    TP_PRESENCA_CH VARCHAR(1),
    TP_PRESENCA_LC VARCHAR(1),
    TP_PRESENCA_MT VARCHAR(1),
    NU_NOTA_CN VARCHAR(9),
    NU_NOTA_CH VARCHAR(9),
    NU_NOTA_LC VARCHAR(9),
    NU_NOTA_MT VARCHAR(9),
    TP_STATUS_REDACAO VARCHAR(1),
    NU_NOTA_COMP1 VARCHAR(9),
    NU_NOTA_COMP2 VARCHAR(9),
    NU_NOTA_COMP3 VARCHAR(9),
    NU_NOTA_COMP4 VARCHAR(9),
    NU_NOTA_COMP5 VARCHAR(9),
    NU_NOTA_REDACAO VARCHAR(9)
);